# Generated by Django 5.2.6 on 2025-09-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='data',
        ),
        migrations.AddField(
            model_name='postagem',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novidade',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
